-- SQLite schema for the local Alongside demo.
-- IDs and timestamps are generated by the application.

PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS profiles (
  user_id TEXT PRIMARY KEY,
  timezone TEXT NOT NULL DEFAULT 'Europe/London',
  onboarding_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  requested_support_mode TEXT,
  selected_support_mode TEXT,
  processing_state TEXT NOT NULL DEFAULT 'created',
  memory_enabled INTEGER NOT NULL DEFAULT 1,
  safety_level TEXT NOT NULL DEFAULT 'normal',
  started_at TEXT,
  ended_at TEXT,
  processing_error_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS transcript_turns (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  turn_index INTEGER NOT NULL,
  speaker TEXT NOT NULL CHECK (speaker IN ('user', 'agent')),
  text TEXT NOT NULL,
  start_ms INTEGER,
  end_ms INTEGER,
  source TEXT NOT NULL CHECK (source IN ('openai', 'elevenlabs_fallback', 'demo')),
  model TEXT,
  audio_path TEXT,
  created_at TEXT NOT NULL,
  UNIQUE(session_id, turn_index)
);

CREATE TABLE IF NOT EXISTS journal_entries (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_id TEXT NOT NULL UNIQUE REFERENCES sessions(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  content_json TEXT NOT NULL DEFAULT '{}',
  user_edited INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memories (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  memory_type TEXT NOT NULL,
  statement TEXT NOT NULL,
  content_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL CHECK (status IN ('proposed','confirmed','rejected','superseded','expired','revoked')),
  explicitness TEXT NOT NULL CHECK (explicitness IN ('explicit','inferred')),
  confidence REAL NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  sensitivity TEXT NOT NULL CHECK (sensitivity IN ('low','medium','high')),
  source_session_id TEXT REFERENCES sessions(id) ON DELETE SET NULL,
  source_turn_id TEXT REFERENCES transcript_turns(id) ON DELETE SET NULL,
  source_quote TEXT,
  valid_from TEXT,
  valid_to TEXT,
  learned_at TEXT NOT NULL,
  invalidated_at TEXT,
  expires_at TEXT,
  superseded_by TEXT REFERENCES memories(id),
  reuse_permission TEXT NOT NULL DEFAULT 'ask_first' CHECK (reuse_permission IN ('allowed','ask_first','never_proactive')),
  revoked_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS entities (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  label TEXT NOT NULL,
  attributes_json TEXT NOT NULL DEFAULT '{}',
  source_memory_id TEXT REFERENCES memories(id) ON DELETE SET NULL,
  revoked_at TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS relations (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  subject_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  predicate TEXT NOT NULL,
  object_id TEXT NOT NULL REFERENCES entities(id) ON DELETE CASCADE,
  valid_from TEXT,
  valid_to TEXT,
  learned_at TEXT NOT NULL,
  invalidated_at TEXT,
  confidence REAL NOT NULL DEFAULT 1 CHECK (confidence >= 0 AND confidence <= 1),
  explicitness TEXT NOT NULL DEFAULT 'explicit' CHECK (explicitness IN ('explicit','inferred')),
  source_memory_id TEXT REFERENCES memories(id) ON DELETE SET NULL,
  revoked_at TEXT
);

CREATE TABLE IF NOT EXISTS interventions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  session_id TEXT REFERENCES sessions(id) ON DELETE CASCADE,
  support_mode TEXT NOT NULL,
  intervention TEXT NOT NULL,
  rationale TEXT NOT NULL,
  context_json TEXT NOT NULL DEFAULT '{}',
  offered_at TEXT NOT NULL,
  accepted INTEGER,
  completed INTEGER,
  helpfulness INTEGER CHECK (helpfulness BETWEEN 0 AND 4),
  burden INTEGER CHECK (burden BETWEEN 0 AND 4),
  later_effect TEXT,
  reuse_permission INTEGER
);

CREATE TABLE IF NOT EXISTS upcoming_moments (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  title TEXT NOT NULL,
  occurs_at TEXT NOT NULL,
  expected_difficulty INTEGER,
  followup_permission INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'upcoming',
  source_memory_id TEXT REFERENCES memories(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS checkin_policies (
  user_id TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0,
  quiet_hours_json TEXT NOT NULL DEFAULT '{}',
  max_per_week INTEGER NOT NULL DEFAULT 0,
  cooldown_hours INTEGER NOT NULL DEFAULT 24,
  preferred_windows_json TEXT NOT NULL DEFAULT '[]',
  paused_until TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS checkin_decisions (
  id TEXT PRIMARY KEY,
  user_id TEXT NOT NULL,
  upcoming_moment_id TEXT REFERENCES upcoming_moments(id) ON DELETE SET NULL,
  decision TEXT NOT NULL CHECK (decision IN ('CHECK_IN','NO_ACTION')),
  reason_code TEXT NOT NULL,
  reason TEXT NOT NULL,
  evidence_ids_json TEXT NOT NULL DEFAULT '[]',
  candidate_time TEXT,
  earliest_allowed_at TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS sessions_user_created_idx ON sessions(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS transcript_session_turn_idx ON transcript_turns(session_id, turn_index);
CREATE INDEX IF NOT EXISTS memories_user_status_idx ON memories(user_id, status);
CREATE INDEX IF NOT EXISTS memories_current_idx ON memories(user_id, memory_type) WHERE status = 'confirmed' AND revoked_at IS NULL;
CREATE INDEX IF NOT EXISTS relations_subject_idx ON relations(user_id, subject_id, predicate);
CREATE INDEX IF NOT EXISTS relations_object_idx ON relations(user_id, object_id, predicate);
